// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtprgclvusugyeesmapv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10cHJnY2x2dXN1Z3llZXNtYXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTA5OTcsImV4cCI6MjA3MTk4Njk5N30.zCloCXPpyy6wSZL0W3gdlOwHfYA1tCWq6fELWinOHb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});